pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.9.1-eclipse-temurin-11' }
      }
      steps {
        sh '''
          javac HelloWorld.java
          java HelloWorld
        '''
      }
    }

    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh '''
          echo 'console.log("Hello from Node.js Frontend!");' > hello.js
          node hello.js
        '''
      }
    }
  }
}
