pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
	sh 'mvn --version'
	sh 'ls -l'
	sh 'pwd'
        //sh 'mvn clean package' // Execute Maven build commands
	//sh 'java -cp target/my-maven-app-1.0-SNAPSHOT.jar com.example.helloworld.App'
      	}
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
