pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
        def user_name = input message: 'Enter your name', parameters: [string(defaultValue: 'machine', description: 'This is for input test', name: 'user_name')]
        echo "Hello ${User_name} ! "
      }
    }
  }
}
