pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        script
        {
        def user_name = input( message:'Enter your name', parameters:[ string (name:'user_name', defaultvalue: 'machine user', description: 'This is description') ] )
        echo "Hello ${user_name} ! "
        }
          }
  }
}
}
