pipeline {
  agent none
  stages {
    stage('Java Hello World') {
      agent {
        docker { image 'openjdk:17' }
      }
      steps {
        sh '''
        echo "public class HelloWorld { public static void main(String[] args) { System.out.println(\\"Hello, World from Java!\\"); }}" > HelloWorld.java
        javac HelloWorld.java && java HelloWorld
        java -version
        '''
      }
    }
    stage('Node.js Hello World') {
      agent {
        docker {
          image 'node:16-alpine'
          args '--user root'  // <-- Run Node container as root to avoid permission issues
        }
      }
      steps {
        sh '''
        echo "console.log('Hello, World from Node.js!');" > hello.js
        node hello.js
        node --version
        '''
      }
    }
  }
}
